# Generated by Django 4.1.3 on 2023-02-04 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index_calculator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_group",
                    models.CharField(help_text="Flow group value", max_length=2),
                ),
                (
                    "fg_descriptive",
                    models.CharField(help_text="Flow group description", max_length=50),
                ),
                (
                    "a_cat_a",
                    models.IntegerField(
                        help_text="Abundance category - A",
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "a_cat_b",
                    models.IntegerField(
                        help_text="Abundance category - B",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "a_cat_c",
                    models.IntegerField(
                        help_text="Abundance category - C",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "a_cat_de",
                    models.IntegerField(
                        help_text="Abundance categories - D/E",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="family",
            name="furse_code",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="genus",
            name="furse_code",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="furse_code",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
