# Generated by Django 4.1.3 on 2023-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index_calculator", "0002_lifescores_alter_family_furse_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="life_fg",
            field=models.CharField(
                help_text="Flow group value", max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lifescores",
            name="flow_group",
            field=models.CharField(
                help_text="Flow group value", max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="life_fg",
            field=models.CharField(
                help_text="Flow group value", max_length=2, null=True
            ),
        ),
    ]
