# Generated by Django 4.1.3 on 2023-02-06 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "index_calculator",
            "0003_family_life_fg_alter_lifescores_flow_group_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PsiScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fssr_group",
                    models.CharField(
                        help_text="Fine Sediment Sensitivity Rating group",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "fssr_definition",
                    models.CharField(
                        help_text="Fine Sediment Sensitivity Rating definition",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "a_cat_a",
                    models.IntegerField(
                        help_text="Abundance category - A",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "a_cat_b",
                    models.IntegerField(
                        help_text="Abundance category - B",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "a_cat_c",
                    models.IntegerField(
                        help_text="Abundance category - C",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "a_cat_d",
                    models.IntegerField(
                        help_text="Abundance category - D",
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="lifescores",
            name="fg_descriptive",
        ),
        migrations.AddField(
            model_name="lifescores",
            name="fg_definition",
            field=models.CharField(
                help_text="Flow group definition", max_length=50, null=True
            ),
        ),
    ]
