# Generated by Django 4.1.3 on 2023-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "index_calculator",
            "0004_psiscores_remove_lifescores_fg_descriptive_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="psi_fssr",
            field=models.CharField(
                help_text="Fine Sediment Sensitivity Rating group",
                max_length=1,
                null=True,
            ),
        ),
    ]
