# Generated by Django 4.1.3 on 2023-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index_calculator", "0007_rename_epsi_w_taxon_epsi_w_p_taxon_epsi_w_r"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="epsi_w_p",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="epsi_w_r",
            field=models.FloatField(null=True),
        ),
    ]
